version: "1.0"
info:
  model: int-scaffold
packages:
- name: SerengetiGHDevOps0408Project
  gitServerName: srcGithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareNew
  gitUsername: ArtiKhareNew
  gitBranch: main
- name: MultiplyPublicService
  version: "6.0"
  gitServerName: srcCtrl_shared_bitbucket_Arti
  gitUrl: https://bitbucket.org/testartiibm
  gitUsername: artikhare
  gitBranch: main
- name: SubstractPublicSvcPackage
  gitServerName: srcCtrl_shared_AzRepos_Arti
  gitUrl: https://dev.azure.com/ArtiKhare/_git
  gitUsername: ArtiKhare
  gitBranch: main
